name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}

    name: Create Release
    runs-on: fedora-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14.x.x'

      - name: Get commit message
        run: |
           echo Commit MSG = $commitmsg

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2